name: Release

on:
  push:
    branches:
      - main
      - stage

jobs:
  clear-stage-cache:
    if: github.ref == 'refs/heads/stage'
    uses: ./.github/workflows/clear-cache.yml
    with:
      cpCode: 1674434
      network: production
      command: delete
    secrets: inherit

  clear-prod-cache:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/clear-cache.yml
    with:
      cpCode: 1680529
      network: production
      command: delete

    secrets: inherit
